# Generated by Django 4.2.6 on 2023-10-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('BugID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Status', models.CharField(max_length=20)),
                ('Severity', models.CharField(max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Bugs',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('StatusUpdateID', models.AutoField(primary_key=True, serialize=False)),
                ('OldStatus', models.CharField(max_length=20)),
                ('NewStatus', models.CharField(max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('BugID', models.ForeignKey(db_column='BugID', on_delete=django.db.models.deletion.CASCADE, to='tickets.bug')),
                ('UpdatedByUserID', models.ForeignKey(db_column='UpdatedByUserID', on_delete=django.db.models.deletion.CASCADE, to='tickets.customuser')),
            ],
            options={
                'db_table': 'StatusUpdates',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.AutoField(primary_key=True, serialize=False)),
                ('CommentText', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('BugID', models.ForeignKey(db_column='BugID', on_delete=django.db.models.deletion.CASCADE, to='tickets.bug')),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='tickets.customuser')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='AssignedToUserID',
            field=models.ForeignKey(db_column='AssignedToUserID', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bugs', to='tickets.customuser'),
        ),
        migrations.AddField(
            model_name='bug',
            name='ProjectID',
            field=models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, to='tickets.project'),
        ),
        migrations.AddField(
            model_name='bug',
            name='ReportedByUserID',
            field=models.ForeignKey(db_column='ReportedByUserID', on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to='tickets.customuser'),
        ),
    ]
