# Generated by Django 4.2.6 on 2023-10-15 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='BugID',
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='UpdatedByUserID',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='AssignedToUserID',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='ProjectID',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='Severity',
        ),
        migrations.AlterField(
            model_name='bug',
            name='ReportedByUserID',
            field=models.ForeignKey(db_column='ReportedByUserID', on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='StatusUpdate',
        ),
    ]
